Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,85 +1,43 @@
-name: Build and Push Chromium
+name: Build and Push Chromium Image
 
 on:
   workflow_dispatch:
 
 jobs:
   check_chromium_version:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     steps:
-      - name: Set up environment
-        run: |
-          mkdir -p .cache
-          echo "Set up environment complete."
-
-      - name: Restore last Chromium version from cache
-        uses: actions/cache@v3
-        with:
-          path: .cache
-          key: chromium-version-cache
-
       - name: Check Chromium Version
         run: |
-          apt-cache madison chromium | grep xtradeb/apps | awk '{print $3}' > .cache/current_chromium_version.txt
+          apt-cache madison chromium | grep xtradeb/apps | awk '{print $3}' > ./cache/current_chromium_version.txt
+          SHORT_VERSION=$(awk -F '.' '{print $1 "." $2}' ./cache/current_chromium_version.txt)
+          echo "short_version=${SHORT_VERSION}" >> $GITHUB_ENV
 
-      - name: Extract Short Version
+      - name: Check Image on Docker Hub
         run: |
-          awk -F '.' '{print $1 "." $2}' .cache/current_chromium_version.txt > .cache/short_chromium_version.txt
-
-      - name: Compare with the last version
-        run: |
-          if [ ! -f .cache/last_chromium_version.txt ]; then
-            echo "No previous version found. Proceeding with build."
-            echo "build_required=true" >> $GITHUB_ENV
-          elif ! cmp --silent .cache/current_chromium_version.txt .cache/last_chromium_version.txt; then
-            echo "New Chromium version detected. Proceeding with build."
-            echo "build_required=true" >> $GITHUB_ENV
-          else
-            echo "Chromium version is up to date. Skipping build."
-            echo "build_required=false" >> $GITHUB_ENV
-          fi
-
-      - name: Clear existing cache (optional)
-        if: env.build_required == 'true'
-        run: rm -rf .cache/current_chromium_version.txt
-
-      - name: Cache the current Chromium version
-        uses: actions/cache@v3
-        with:
-          path: .cache
-          key: chromium-version-cache
-          restore-keys: chromium-version-cache
+          curl --silent -f -lSL https://hub.docker.com/v2/repositories/erolatex/selenoid_chromium/tags/${{ env.short_version }}/ || echo "Not Found" > check_result.txt
+        id: check_docker
 
   build_and_push:
     needs: check_chromium_version
     runs-on: ubuntu-latest
-    if: env.build_required == 'true'
+    if: failure()
     steps:
-      - name: Clone Dockerfile Repository
-        uses: actions/checkout@v2
-        with:
-          repository: erolatex/selenoid_chromium_dockerfile
-          path: dockerfile_repo
-
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+          username: ${{ secrets.DOCKERHUB.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKERHUB.DOCKER_PASSWORD }}
+
+      - name: Clone Repository
+        uses: actions/checkout@v2
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
       - name: Build and Push Docker Image
         run: |
-          cd dockerfile_repo
-          docker buildx build --no-cache --platform linux/amd64,linux/arm64 \
-            -t erolatex/selenoid_chromium:$(cat ../../.cache/short_chromium_version.txt) \
+          docker buildx build --platform linux/amd64,linux/arm64 \
+            -t erolatex/selenoid_chromium:${{ env.short_version }} \
             -t erolatex/selenoid_chromium:latest \
             --push .
-        
-      - name: Post Log in to Docker Hub
-        run: echo "Docker image build and push completed."
-
-      - name: Save the current Chromium version
-        run: cp .cache/current_chromium_version.txt .cache/last_chromium_version.txt
